//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tata_prices")]
pub struct Model {
    pub time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Double", nullable)]
    pub price: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub volume: Option<f64>,
    pub currency_code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
